/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DaysOfTheWeek;
import javax.swing.*;


public class App {
    

    public static void main(String[] args) {
        String day;
        String[] daysOfWeek = new String[7];
        
        for(int i = 0; i<daysOfWeek.length;i++){
        day = JOptionPane.showInputDialog("Type In Any Day Of The Week");
        
        daysOfWeek[i] = day;
        }
        
        JOptionPane.showMessageDialog(null, daysOfWeek);
    }
}
